# packages required for testing and development
name: cacheml
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.9.*
  - joblib
  - s3fs
  - pycryptodome
  - ipython
  - click
  - pandas
  - numpy
  - pytest
  - pip
  - pip:
    - twine
