name: dvl
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.9.*
  - jupyter
  - ipython
  - scikit-learn=0.24.*
  - pandas=1.2.*
  - numpy=1.20.*
  - snakemake
  - joblib
  - s3fs
  - cryptography
  - click
  - pip
